


=encoding UTF-8

=head1 NAME

Unicode::Confuse - abstract here.

=head1 SYNOPSIS

    use Unicode::Confuse;

=head1 VERSION

This documents version 0.01 of Unicode-Confuse
corresponding to L<git commit f61f07ecb8c6481f355dd97126b39931a3c8d28e|https://github.com/benkasminbullock/unicode-confuse/commit/f61f07ecb8c6481f355dd97126b39931a3c8d28e> released on Wed Apr 14 09:47:59 2021 +0900.

=head1 DESCRIPTION

=head1 FUNCTIONS



=head1 AUTHOR

Ben Bullock, <bkb@cpan.org>

=head1 COPYRIGHT & LICENCE

This package and associated files are copyright (C) 
2021
Ben Bullock.

You can use, copy, modify and redistribute this package and associated
files under the Perl Artistic Licence or the GNU General Public
Licence.



